# Book configuration
# Learn more at https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title: Data 140 Textbook
author: Ani Adhikari
email: adhikari@berkeley.edu
logo: content/images/logo/sp22_ugarte_logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
#execute:
#  execute_notebooks: force

# Don't run these files.
exclude_patterns: ["LICENSE.md"]

# Favicon
html:
  favicon: content/images/favicon/favicon.ico
#######################################################################################
# Interact link settings

# Repository information
repository: 
  url: https://github.com/prob140/textbook 
  branch: gh-pages

# Tells Jupyter Book to add JupyterHub links to pages
launch_buttons:
  notebook_interface: classic
  jupyterhub_url: https://prob140.datahub.berkeley.edu


#######################################################################################
# Option to add a Google analytics tracking code

# Navigate to https://analytics.google.com, add a new property for your jupyter book and copy the tracking id here.
google_analytics:
  mytrackingcode:
